services:
  postgres:
    image: postgres:15-alpine
    container_name: fintrack-postgres
    restart: always
    environment:
      POSTGRES_USER: fatahul
      POSTGRES_PASSWORD: postgres089
      POSTGRES_DB: fintrack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
